### PR TITLE
The sanitizer config fixed

### LINKED ISSUE #44: Saving resets text formatting
I can use hotkeys like SHIFT+ENTER, CMD+B in a Header block. But when I save it resets. All formatting disappears.

So it has different look in the editor and in final HTML.

How to make hotkeys unavailable in the Header block?

There is no such problem in block Code https://github.com/editor-js/code

### PR DESCRIPTION
**Pull request by neSpecc**
Resolves #44

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -235,12 +245,14 @@ class Header {
    */
   static get sanitize() {
```
Comment (neSpecc) [inline src/index.js:246]: here is a fix
