### PR TITLE
fix(undefined data): undefined issue in normalizeData member function

### LINKED ISSUE #112: You broke it
Getting `TypeError: Cannot read properties of undefined (reading 'toString')` in next.js with react-editor-js

image
 fuck and I thought why it does not work for me and works for everyone else :cry:

### PR DESCRIPTION
**Pull request by dependentmadani**
## Problem:
An issue of reading undefined by toString.

## Cause:
The level parameter in data object is not checked for possibility of undefined.

## Solution:

Check on the level content availability in the object, so it can be converted into string.

Resolves #112

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -145,14 +145,14 @@ export default class Header {
...
+    const newData: HeaderData = { text: '', level: this.defaultLevel.number };
 
     if (typeof data !== 'object') {
-      data = {text: '', level: this.defaultLevel.number};
+      data = { text: '', level: this.defaultLevel.number};
     }
 
     newData.text = data.text || '';
-    newData.level = parseInt(data.level.toString()) || this.defaultLevel.number;
+    newData.level = data.level ? parseInt(data.level.toString()) : this.defaultLevel.number;
```
Comment (neSpecc) [inline src/index.ts:155]: how level can be undefined here?

Comment (dependentmadani) [reply src/index.ts:155]: probably with the casting of `HeaderData`

Comment (neSpecc) [reply src/index.ts:155]: maybe `typeof data !== 'object'` is not working as expected? Have you managed to reproduce the problem? Try adding a Header via Toolbox and check what is the `data` exactly?

Comment (dependentmadani) [reply src/index.ts:155]: I tested it locally, it seems to be working fine I guess

Comment (neSpecc) [reply src/index.ts:155]: yes, but the reason is still not clear

Comment (neSpecc) [reply src/index.ts:155]: I mean there is an issue with types somewhere

Comment (neSpecc) [reply src/index.ts:155]: seems like in `ConstructorArgs` the data should be `HeaderData | {}`

Comment (dependentmadani) [reply src/index.ts:155]: I guess if `HeaderData | {}` is used instead of `HeaderData` for data, we will need to check for availability of level and text inside the object.

Comment (dependentmadani) [reply src/index.ts:155]: After debugging, it seems that the data received in `normalizeData` function is an empty object. Before using header tool, the data is an empty object. Until initializing and using header tool, by filling the text, then the object get filled with its appropriate infos.

Comment (neSpecc) [reply src/index.ts:155]: yes, statement is ok, but we need to improve types as well

Comment (neSpecc) [reply src/index.ts:155]: and also `if (typeof data !== 'object') {` will never fired

Comment (dependentmadani) [reply src/index.ts:155]: no it will not. I guess should check data content instead

Comment (neSpecc) [reply src/index.ts:155]: you can use a type guard util like this

```ts
isHeaderData(data: any): data is HeaderData {
  return (data as HeaderData).text !== undefined;
}
```

File: src/index.ts [hunk 2]
```diff
@@ -116,7 +116,7 @@ export default class Header {
      * @type {HeaderData}
      * @private
      */
-    this._data = this.normalizeData(data);
+    this._data = this.normalizeData(data as HeaderData);
```
Comment (neSpecc) [inline src/index.ts:119]: redundant cast

File: src/index.ts [hunk 3]
```diff
@@ -145,10 +156,10 @@ export default class Header {
    * @private
    */
   normalizeData(data: HeaderData): HeaderData {
```
Comment (neSpecc) [inline src/index.ts:158]:
```suggestion
  normalizeData(data: HeaderData | {}): HeaderData {
```

**Comment by Aryanop0914** [comment]
any update on it how can it be solved?

**Review by neSpecc — APPROVED** [review]
